### ISSUE TITLE
Signal ID fails at certain frequencies with small span hiding real signals

### ISSUE THREAD

**Issue by erikkaashoek** [jankae/LibreVNA#110]
This was tested with the latest FW and PC application and all settings reset to default.
In SA mode, at certain frequencies a signal disappears when reducing the span.
Example frequencies:
1570000000
1700000000
1830000000
1960000000
2090000000
2220000000
2350000000
2480000000
2610000000
2870000000
3000000000
3130000000
3260000000
3390000000
3520000000
3650000000
3910000000
4170000000

The attached 3 images show the stepwise disappearing of the signal with decreasing span
10MHz span
![image](https://user-images.githubusercontent.com/4621892/172316364-9518867a-28ae-4e5a-9e2b-1c15a70e9322.png)

1MHz span
![image](https://user-images.githubusercontent.com/4621892/172316527-9ba17476-24c4-4c4d-9c0b-abd6f302c348.png)

100kHz span
![image](https://user-images.githubusercontent.com/4621892/172316641-16adf2ad-a359-4010-85fe-66883e159b18.png)

**Comment by jankae** [comment]
All settings reset to default means that you are using an RBW of 10 kHz? Could you share the setup file please? Probably easier than confirming every setting by text.

**Comment by erikkaashoek** [comment]
Settings
[settings.zip](https://github.com/jankae/LibreVNA/files/8852096/settings.zip)

RBW was set to 1kHz

**Comment by jankae** [comment]
I was unable to replicate the issue (using your setup file, enabling signal ID and only changing the span):
10 MHz span:
![10MHz](https://user-images.githubusercontent.com/16818866/172355877-8dcf9561-c349-4ec2-a9a9-70efdce7fb06.png)
1 MHz span:
![1MHz](https://user-images.githubusercontent.com/16818866/172355929-aa891ccf-e217-48c2-a1cd-1effd7a85687.png)
100 kHz span:
![100kHz](https://user-images.githubusercontent.com/16818866/172355960-e1c29a28-171e-49af-ad97-2635ca4fe1fd.png)

What are you using as a signal source?

**Comment by erikkaashoek** [comment]
You are not testing one of the frequencies in my list. It only happens at specific frequencies.
Try 3GHz, it only happens on 3GHz +/- some kHz

**Comment by jankae** [comment]
Ah, my bad. Yes, at 3 GHz I also see the problem. Probably another issue of the PLL unable to reach the exact frequency, I'll try to fix it soon.

**Comment by erikkaashoek** [comment]
The problem appears every 13MHz

**Comment by jankae** [comment]
Yes, that fits the suspected PLL divider issue (PLL reference frequency is 104 MHz, 8 * 13 MHz).
I was actually already compensating for the PLL divider accuracy by shifting the 2.LO. But I forgot to adjust the direction of the shift during the signal ID steps (1.LO sits on either side of the signal frequency depending on the signal ID step). The problem is hidden during larger spans because there are actually multiple frequency points captured per displayed point. If at least on point doesn't have the problem, the signal will show up (assuming a positive peak detector).

Solution: check if 1.LO is below or above of the frequency of interest and shift 2.LO accordingly. During my tests, all signals showed up now. Also fixed some smaller other issues while being in there.

**Comment by erikkaashoek** [comment]
I've tested the new FW and all seems to be OK, will you close the issue?

**Comment by jankae** [comment]
Yes, thank you for confirming
