### ISSUE TITLE
SCPI Command and query VNA:ACQ:SINGLE always seems to return ERROR

### ISSUE THREAD

**Issue by Ivesvdf** [jankae/LibreVNA#113]
Steps to reproduce: open LibreVNA GUI v1.3.0, with the LibreVNA on the latest published FW image. Open default config, meaning VNA with sweep type set to frequency. 

Over SCPI, execute the following commands
![image](https://user-images.githubusercontent.com/264447/173233214-33893ba7-897b-4669-ae5f-c826dd1932e1.png)

Every possible variation of the single command fails with "error". I also can't find any reference to single mode in the UI, so I'm unsure how to test it through the GUI. 

Expected behavior: 
See reference manual
![image](https://user-images.githubusercontent.com/264447/173233282-304c4901-d049-4fad-b9c1-45042d94338b.png)

**Comment by jankae** [comment]
Yes, that is the expected behavior with that version. The "single"-command was added by d84d3e80, which happened after the 1.3.0 release. Until I create the next release, you'll need to use the latest development version (download compiled versions of each commit here: https://github.com/jankae/LibreVNA/actions)

**Comment by Ivesvdf** [comment]
Ok great, thank you. Closing.
