### ISSUE TITLE
GUI: touchstone viewer

### ISSUE THREAD

**Issue by horror-vacui** [jankae/LibreVNA#138]
### Summary

It would be a nice and I hope easy to implement feature to display one and two port touchstone files (.s1p, .s2p). So instead of reading out the data from the LibreVNA device, they would be loaded from a file.

An additional nice option would be if such imported data traces could be permanently added to the display, while a live readout (i.e. continuous measurement) from the LibreVNA is happening.

I am a new user, and though I have been searching for this option I have not found it. Let me know if something similar has already been implemented.

### Paths to implement it

Replace data coming from the device with data coming from a file.

### Extra information

.

**Comment by jankae** [comment]
Already possible, check out this button:
![grafik](https://user-images.githubusercontent.com/16818866/178971876-ca174714-bd58-48ef-baf8-5ac24364574f.png)

**Comment by horror-vacui** [comment]
> Already possible, check out this button

Many Thanks! I've only looked in the menus and into the "+" button, but missed that icon. I have a black system theme (and probably a terrible monitor), and lines in the import/export icons stayed black, making the drawing on the icon very hard to see.  The lines in the other icons where white, but not these ones. There is a similar issue in the traces field:
![image](https://user-images.githubusercontent.com/31111509/178974608-345f058f-af0e-49f7-a653-17f93c49ffc4.png)
Please take it as information, and not a critic. I like the tool. Actually I am really glad that the GUI recognizes the system theme at all.

It would be great to load in multiple files, and not just a single one. I guess it is a limitation in the File API.

I could not copy the exact build from the About window (could be a nice feature it implement), but I use this version:
![image](https://user-images.githubusercontent.com/31111509/178975063-059ae643-99f1-48af-80ee-25ffe4460f0a.png)
I am using it on Manjaro Linux with KDE. I could  imagine that most these little nuances are only present in my config.

Many thanks for the great software and hardware! Keep up the good work!

**Comment by jankae** [comment]
Hm, I haven't tried it with a dark theme yet, probably quite a few things that don't look great. The problem is that a lot of the icons are just simple .pngs regardless of the theme. Most general GUI stuff is handled by Qt which seems to recognize the theme. But any custom icon will just stay exactly the same. I am not too familiar with GUI programming, especially when it comes to creating graphics. I might look into it at some point, but it probably won't happen soon, sorry.

> I could not copy the exact build from the About window (could be a nice feature it implement)

Should be possible:
![grafik](https://user-images.githubusercontent.com/16818866/178978688-df1b7284-0947-42ff-ae6f-43f354eb769c.png)

> Many thanks for the great software and hardware! Keep up the good work!

Thank you, I'll to my best :)
