### ISSUE TITLE
 TDR Impedance Math (off) then (on) returns to Impulse Response

### ISSUE THREAD

**Issue by dna35** [jankae/LibreVNA#173]
### Summary

The preference would be to return to the previous Math function of Impedance. Not doing so, requires opening the Primary Y axis Setup and selecting Impedance from the pull-down menu.

1- Original TDR Math mode
![TDR Impedance](https://user-images.githubusercontent.com/36786668/207229596-b834f071-fa27-45fc-b7bd-4137130bc3e5.png)
Fig.1 

2-Turn off Math goes to Frequency Domain Magnitude. Okay, unless previous desirable.
![Math Off Frequency Domain Magnitude](https://user-images.githubusercontent.com/36786668/207229676-1f474706-30f6-4c22-9669-3f08194f6815.png)
Fig. 2

3- TDR Math on goes to Impulse Response - Definitely want to return to Impedance or last setting of Fig.1.
![TDR Math On Impulse Respose instead of Impedance](https://user-images.githubusercontent.com/36786668/207230387-67332e31-9acc-4300-b61c-0095915d58a4.png)
Fig. 3

4- Return to TDR Impedance instead of Impulse Response
![TDR Impedance](https://user-images.githubusercontent.com/36786668/207231231-799af479-ea9e-43f2-9e0c-4907553465ed.png)
Fig. 4

### Paths to implement it

Set the Math switch to retain the last setting in the Time Domain or Frequency Domain mode.

### Extra information

None

**Comment by jankae** [comment]
Unfortunately, these are completely different parts of the software. The trace (and the math switch) only determines the output domain of the trace, the graph determines the axes configuration.

When you turn off the math, the trace output data changes from time domain to frequency domain. The graph notices that change and attempts to configure itself to match the new domain. The same thing happens when you turn the TDR back on.
The graph has no memory of its last configuration, so it defaults to some standard settings for the Y axes. I suppose it is possible to store the previous configuration in the graph as well but I am not sure yet if I will go down that route.
For now, you can just change the graph behavior in the preferences:
![grafik](https://user-images.githubusercontent.com/16818866/207293694-223faf49-76a4-4e63-a8ca-5d84f7fc25bd.png)
This will prevent the graph from changing any axes configuration when the trace data domain changes but it will instead remove the trace from the graph and you need to manually add it back. Of course, adding the trace back will require you to set up the graph for the correct domain. You could use two graphs, one set up for frequency and one for time, that way you will always have one that is configured correctly for the trace.

**Comment by dna35** [comment]
Jan, I have tried the "Remove changed trace from all unsupported graphs" and have applied it to get a better understanding.

Thank you for bringing that to my attention.
