### ISSUE TITLE
Build #626 and below appears to be more useful in Dual VNA mode

### ISSUE THREAD

**Issue by dna35** [jankae/LibreVNA#174]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.2-b67275831
OS: Windows 10 Version 2009
CPU Arch: x86_64

### Steps to reproduce

This is more of a milestone checkpoint or feasibility test report.

Even though the scroll bar is an excellent needed feature, build #626 is more useful and stable. Maybe it can be installed right after build #626. 

The GUI slows down in Dual VNA mode after build#626 with the introduction of the Toggle switch. The Toggle for de-embedding traces is very nice as long as the graph scans and stability are not affected. At this point I have rolled back to the more stable build#626.

I realize this is a WIP effort and hope that the new features will materialize. However, robust functionality is preferable.

### Expected behavior

All graphs in the frequency domain should function in a reasonable manner and at a reasonable speed. The TDR functionality is primo and hopefully not compromised. It may actually be considered a stress test for useability or the Gold Standard.

### Extra information & Setup and Calibration files

As a further recommendation, perhaps if necessary, the Toggles could be used in single VNA mode only and grayed out for multi VNA use to maximize speed.

**Comment by jankae** [comment]
Looks like this was caused by unnecessarily emitting a signal for every added de-embedding point. That signal caused the trace widget to be updated all the time (even when nothing relevant changed). I have now changed the code to only emit the signal when the first de-embedding point is added and my sweep speed is now unchanged when I enable de-embedding with two VNAs connected.

**Comment by dna35** [comment]
Fantastic, it is now working very well!
