### ISSUE TITLE
Poor lines

### ISSUE THREAD

**Issue by Chorbu** [jankae/LibreVNA#201]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.2-54de9fd6b
OS: Windows 10 Version 2009
CPU Arch: x86_64

### Steps to reproduce

Since a few months i have strange traces with a lot of non linearity traces. Calibration is OK,.
Il tryed to change USB cable, and try it on another PC : Same thing happened
My hamradios are off (VHF and UHF) , no spurious emissions near the VNA.
I tried to change IF1 and IF2 but without result,
Actual values are

![ADC](https://user-images.githubusercontent.com/55191367/226204245-bec7dda1-ed7f-4e43-8cd0-e2f9f8629306.jpg)

I also put a good power supply by connect a DC power supply >2A (same result)

I hope this is not due to a degradation of components inside VNA.

![Capture d’écran 2023-03-19 201051](https://user-images.githubusercontent.com/55191367/226203627-bfaf31c3-74a2-42d7-86a4-107ad888b13d.jpg)

### Expected behavior

What do you think about that ?

Could you give me original values of IF1 and IF2 ?

### Extra information & Setup and Calibration files

no extra information

**Comment by jankae** [comment]
Hm, looks strange. Your IF values are at the default. Can you please try older firmware/GUI versions to determine whether this is a hardware or software problem? You can also enable "capture raw receiver values" in the preferences (either under Debug or LibreVNAUSBDriver, depending on your GUI version). This gives you the option to create traces from just the port or reference receiver instead of Sxy. That might get us additional insight about the source of these spikes/noise.

**Comment by Chorbu** [comment]
I 've just try this software and firmware (before is not possible)
![Last](https://user-images.githubusercontent.com/55191367/226205761-18231e8e-a044-4ebb-bd5e-77f312afd3d4.jpg)


Same issue....

**Comment by jankae** [comment]
Okay, I think that rules out the possibility of a new bug, I think other people would have noticed and notified me by now if that was the case.

Please look into the raw receiver values. Another thing you could try it starting the manual control dialog, enabling all PLLs and the amplifier and take a screenshot of that. On its own this is probably not that helpful but if I compare it to my LibreVNAs we might see that some values are off/different.

**Comment by Chorbu** [comment]
Here is the screenshot of Manual control dialog
![PLL](https://user-images.githubusercontent.com/55191367/226206812-4040bfe9-b968-4226-b16f-0738919f5fb3.jpg)

I activate Capture RAW receiver but i don't know where the values are saved...

**Comment by Chorbu** [comment]
i forgot to activate Amplifier...

**Comment by Chorbu** [comment]
But same issue

**Comment by jankae** [comment]
> I activate Capture RAW receiver but i don't know where the values are saved...

You can change a trace to use the raw receiver value here:
![image](https://user-images.githubusercontent.com/16818866/226207167-a0e3bb25-10b8-4027-b6a0-a6b33c67530b.png)
All parameters except for RawPort1Stage1Ref and RawPort2Stage0Ref would be interesting to me.

> But same issue

Can you please post a screenshot of the manual control dialog with the amplifier enabled? The ADC values should get much larger.

**Comment by Chorbu** [comment]
OK thank you

![PLL](https://user-images.githubusercontent.com/55191367/226207387-09481c52-5393-4a16-a1b8-4665bcddb0f1.jpg)

**Comment by jankae** [comment]
I assume you still have something connected to the ports? Otherwise the port 2 ADC values are much too high. But otherwise that looks good. This is from my device:
![image](https://user-images.githubusercontent.com/16818866/226207708-3c3f8d64-c245-4a54-b8d2-7fdd724ca372.png)

**Comment by Chorbu** [comment]
Here all the screens for RAW
![1](https://user-images.githubusercontent.com/55191367/226207917-1707886c-eb5e-4acc-abd3-6161357c4d8d.jpg)
![2](https://user-images.githubusercontent.com/55191367/226207918-1a709a9a-c8f5-4573-90b4-e563aa5500aa.jpg)
![3](https://user-images.githubusercontent.com/55191367/226207919-dfc87c96-39b9-4970-aece-695f46c982e9.jpg)
![4](https://user-images.githubusercontent.com/55191367/226207923-75694f36-ed3d-454a-b9da-5c63a7c02be0.jpg)
![5](https://user-images.githubusercontent.com/55191367/226207924-6bb055dd-e31f-412a-9117-a8b37233a831.jpg)
![6](https://user-images.githubusercontent.com/55191367/226207925-5874338a-8b12-4666-8dc6-e392109f8f75.jpg)

**Comment by Chorbu** [comment]
I i have a band stop filter 144MHz to 148MHz connected to my VNA

**Comment by Chorbu** [comment]
So I'm going to stop it for tonight, tomorrow work and up at 6am.

Thank you in advance Jan, good night to you too.
Patrick

**Comment by Chorbu** [comment]
Oh i ve just see you've already add APPLY button for my previous request !!!! Thank you for your extreme speed !!!!

Good night 
Patrick F5SUE

**Comment by jankae** [comment]
You raw receiver data doesn't reveal any obvious issues (maybe a bit too much noise on the reference receiver data, but your problematic signals are coming from the port receivers). Just to make sure that it isn't from the DUT: what happens if you change the setup? (e.g. just measuring a direct through).

You can also try to reduce your IF bandwidth. Some narrow band filters have quite the long settling time and might not have fully settled in the time the VNA takes to measure a point for higher IF bandwidths. That could easily result in the measurement data you are getting.

**Comment by Chorbu** [comment]
With 500Hz IF BW or more is the same issue. Tomorow evening i will try again my other filters, splitter, coupler etc...

**Comment by Chorbu** [comment]
THRU connected (I SMA) after calibration

S12 is Magnitude
![THRU](https://user-images.githubusercontent.com/55191367/226209091-53365792-ff03-4698-957c-ace0ef971719.jpg)

**Comment by jankae** [comment]
Yeah, that is too much noise on the reference receiver. Same settings on my VNA:
![image](https://user-images.githubusercontent.com/16818866/226210087-16ab2dc6-8a75-4718-9d6a-e37e0403707b.png)
I am unsure why you are getting that. Let's both sleep on it, maybe there are new ideas tomorrow.

**Comment by Chorbu** [comment]
Yes i saw that !!! Ther is a problem with my receive port !

**Comment by Chorbu** [comment]
Thank you Jan, thanks for your help. Have a good night
Patrick

**Comment by Chorbu** [comment]
Hello Jan,

The BandPass filter is REACTEL Fcenter 2150 MHz  réf SN86-1 (surely from an old SNA i supposed).

Here are the test comparaison with an ARINST VNA (without calibration made).
You can see behind the stop band filter for 2m fréquency

![IMG_0861](https://user-images.githubusercontent.com/55191367/226720360-53962f73-8ef9-4737-b495-16d31dd7ec7c.jpg)
![IMG_0862](https://user-images.githubusercontent.com/55191367/226720368-86c5ce81-559d-403a-ab3f-46c326af2fde.jpg)




Bests Regards
Patrick

**Comment by Chorbu** [comment]
Jan,
Here 2150 Bp Filter with the LibreVNA spectrum analiser with tracking

![Spectrum analyser](https://user-images.githubusercontent.com/55191367/226724534-0c1d4953-ffd1-47d8-83f2-6810e4842045.jpg)

And Here the 2m Stop band filter with my old HP8568B analyser with HP8444A tracking generator

![IMG_0864](https://user-images.githubusercontent.com/55191367/226724829-0b6eacd8-9ccb-4b9a-b66e-0b502e329fce.jpg)

**Comment by jankae** [comment]
Okay, did you check it with 10 Hz IF bandwidth as well? Just to rule out the settling time issue I mentioned.

**Comment by Chorbu** [comment]
Hi Jan,

I've just made the test with 10 Hz IF BW and it seems good with the 2150 MHz bandPass filter.

![With 10 Hz IF BW bis](https://user-images.githubusercontent.com/55191367/227009237-1450e3de-b23d-47c8-9c08-6c16a54c79da.jpg)

I will try with the 2m stop band filter.

**Comment by Chorbu** [comment]
Same with 40 Hz IF BW 

![With 40 Hz IF BW](https://user-images.githubusercontent.com/55191367/227018579-57ce6bc3-d7b3-4da1-86cc-bbd6a7815c65.jpg)

**Comment by Chorbu** [comment]
So it works well under30 Hz IF BW, so i think you can close this PR.

Many thanks, have a good evening.
Patrick

**Comment by jankae** [comment]
Okay, thanks for all the additional measurements. Some background information on the "problem", because you might notice that other VNAs can work at higher IF bandwidths: what matters is the overall time after which the stimulus signal is stable. If there is a sufficient delay before sampling the ADCs, you can also take measurements at much higher IF bandwidths. Some VNAs also have a special mode to introduce additional delay there. The LibreVNA currently has no option for any delay (apart from the fixed delay due to the locking of the PLLs) and it is also optimized for fast sweep speed.

Selecting a lower IF bandwidth has a similar effect because more ADC samples are needed (which takes more time). As long as most of the samples are taken when the DUT has fully settled, you will get valid results. Otherwise you could end up with very noisy data - sometimes only in some frequency bands.

I'll go ahead and close this now.
