### ISSUE TITLE
Signal Generator Output drifting w.r.t. Ref Out

### ISSUE THREAD

**Issue by cweickhmann** [jankae/LibreVNA#209]
### LibreVNA Version

LibreVNA Version (64 bit): 1.4.0-7f6b78992
OS: Ubuntu 22.04.2 LTS
CPU Arch: x86_64

### Steps to reproduce

- LibreVNA GUI App is launched
- Function Tab "Signal Generator" is selected
- Ref in Internal is selected
- Ref out 10 MHz is selected
- Frequency is set to 50 MHz
- Port 1 Output is enabled

Now, Ref Out and Port 1 are both connected to the same Oscilloscope. Triggering is set up to the Input receiving Ref Out.

When observing the input connected to Port 1, the signal drifts.

This can be observed with Ref Out 100 MHz, or with another Frequency for the Signal on Port 1 in the same way, or on Port 2 instead of Port 1.

### Expected behavior

I would expect the output signal to be phase-locked with respect to the Ref Out signal.

### Extra information & Setup and Calibration files

[siggen_drifting_signal.setup.txt](https://github.com/jankae/LibreVNA/files/11295879/siggen_drifting_signal.setup.txt)

Firmware is the latest release 1.4.1 .

**Comment by jankae** [comment]
This is normal and a hardware limitation of the PLLs. They can't reach any frequency precisely due to the limited fractional-N divider. Your 50 MHz output is very close to 50 MHz but not spot on, as a result you see the drift.

This is not a problem in VNA operation because the deviation from the set frequency is small enough to still fall inside the IF bandwidth (or the internal LO frequencies are adjusted to correct for the frequency error). In the signal generator mode you just have to live with this, sorry.

**Comment by cweickhmann** [comment]
Thanks for the prompt reply!
That also explains why the drift goes wild for other frequencies.
Is this a limitation of this *particular* hardware, or a general problem even with hardware PLLs (I'm assuming the PLL you're talking about is on fabric in the FPGA)?

Would've been a nice hack for my setup here. Now I'll just hijack another clock coming from the device I'm working on. Hopefully, that's not drifting.

**Comment by jankae** [comment]
> I'm assuming the PLL you're talking about is on fabric in the FPGA

No, I am referring to the MAX2871 PLL which is used for the RF frequency generation. But I think this is a general issue of PLLs (and to a lesser extend, DDS). You are always limited to a frequency resolution. In this case it just looks weird because you are trying to generate an integer multiple of the reference frequency - I think anyone would assume that should be possible. But in this case, the reference frequency for the main PLLs is sitting at 104 MHz and dividing that down to exactly 50 MHz (or 100 MHz) is not possible with the MAX2871 PLL.

In theory, it is possible to adjust the LibreVNA firmware to use a different PLL reference frequency and by carefully selecting that it should give you a 50/100 MHz output that is locked to the 10 MHz reference output. But this most likely messes with other frequency planning in the device, so I don't think I will touch this. But if you are up for the challenge (and just want to use the signal generator mode), you could try that. This is the define you are looking for:
https://github.com/jankae/LibreVNA/blob/1aaba21723acd9a4bfe541766c3ec88cc0391b4e/Software/VNA_embedded/Application/Hardware.hpp#L44

I haven't touched the frequency planning in quite a while but if I remember correctly, you just need to adjust this define and everything should still work. I'd start by setting this to the same frequency you are using on the reference output. Might be worth a try.

**Comment by cweickhmann** [comment]
I'll have a look! It might be a little bit overkill for my current purpose. I was trying to check an ADC that produced funny data and just wanted to have a test signal somehow locked to the clock. But your advice above might actually explain part of my problem there. So double thanks!
