### ISSUE TITLE
board fab from KiCad derived manufacturing files / layer stackup and GCPW

### ISSUE THREAD

**Issue by jreeve-nl** [jankae/LibreVNA#8]
Hello there,

Is anyone having boards made currently?  Any going spare?  OSHpark quote is $185 US for 3 and I was thinking if I'm lucky I'll only need a single board (!)  I'll pay for the fractional cost + shipping.

I see gerbers produced for Macrofab too by the build_all.bat script.  The source files are common between the two sets of outputs.  This means that no dimensioning of the GCPW is performed based on the fab and do I understand from that, the OSHpark and selected Macrofab layer stackup are identical?

I saw some discussion about pulling back of planes to get the GCPW characteristic impedance correct (at least as calculated without doing the full EM sim).  Which values were used for epsilon_r and the dielectric thickness for example?  Sorry if this has been covered and I think the answer is that at these tolerances it might not matter all that much.

**Comment by jankae** [comment]
If you read #7 you'll know that the KiCad files are not completely ready for production yet. At the moment I would recommend the Eagle-generated gerbers for you, see also [here](https://github.com/jankae/VNA2/issues/6#issuecomment-718963185).

For production, I suggest jlcpcb with the JLC7628 stackup, this is what I used for the prototypes. The RF traces were calculated according to their provided epsilon_r but I agree, due to tolerances it probably is not that exact.
