### ISSUE TITLE
Load model circuit

### ISSUE THREAD

**Issue by ellits3** [jankae/LibreVNA#86]
Hi Jan,
according to the code calkit.cpp it seems to me that the load model is according the following schematic:
![Load_Model_LibreVNA](https://user-images.githubusercontent.com/99440958/154808962-22fe3102-7a81-4b6f-b52d-e506e11c5d7d.png)
whereas in this document from Anritsu
[http://anlage.umd.edu/Anritsu_understanding-vna-calibration.pdf](url)
on page 16 this arrangement with L directly in series to R is shown for their load model:
![Load_Model_Anritsu](https://user-images.githubusercontent.com/99440958/154809019-b148d4b8-1f3d-4355-b690-14a35ac2dd95.png)
Therefore I'm wondering if there is a standard circuit model for the load? 
If so, this should be implemented (if it isn't already).
If not, it would be good to have the possibility to choose one of both arrangements it in the "Edit Calibration Kit"-window.
At least it would be helpful to show the model circuit in the window to avoid any confusion.
Many thanks in advance.

**Comment by jankae** [comment]
Hi, I am pretty sure that I have seen both models in some documents but now I can only find the Anritsu version. I have added a new setting to the calibration kit that lets you select between the models:
![image](https://user-images.githubusercontent.com/16818866/156159639-5d0e9fc2-07c0-445e-adb8-907a71b79cf8.png)
* Series L first is the model as it was used before in the LibreVNA
* Shunt C first is the Anritsu model

In order to not break existing calibration kit files, it behaves like this:
* When constructing a new calibration kit, "Shunt C first" is selected (Anritsu model is the new default)
* When opening a stored calkit file which does not contain this setting (e.i. it was created before I added this setting), it will use "Series L first" to keep the same calculations that have been used before
